check:
	@echo "command to run Unit test: make <options>"
	@echo "options are:"
	@echo "1)test_a_negativeSubTest "
	@echo "2)test_b_negativeContextDestroy"
	@echo "3)test_c_pattern"
	@echo "4)test_d_subscribe"
	@echo "5)test_e_publish"
	@echo "6)test_f_init"
	@echo "7)test_g_createContext"
	@echo "8)test_h_contextDestroy"

test_a_negativeSubTest:
	python3.6 UnitTest_dba.py TestDBA.test_a_negativeSubTest

test_b_negativeContextDestroy:
	python3.6 UnitTest_dba.py TestDBA.test_b_negativeContextDestroy

test_c_pattern:
	python3.6 UnitTest_dba.py TestDBA.test_c_pattern

test_d_subscribe:
	python3.6 UnitTest_dba.py TestDBA.test_d_subscribe

test_e_publish:
	python3.6 UnitTest_dba.py TestDBA.test_e_publish

test_f_init:
	python3.6 UnitTest_dba.py TestDBA.test_f_init

test_g_createContext:
	python3.6 UnitTest_dba.py TestDBA.test_g_createContext

test_h_contextDestroy:
	python3.6 UnitTest_dba.py TestDBA.test_h_contextDestroy
