# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define OpcuaExport service
  ia_opcua_export:
    depends_on:
      - ia_common
    build:
      context: $PWD/../OpcuaExport
      dockerfile: $PWD/../OpcuaExport/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
    read_only: true
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_opcua_export:${EII_VERSION}
    container_name: ia_opcua_export
    hostname: ia_opcua_export
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m    
    environment:
      AppName: "OpcuaExport"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}

      # MessageBus Endpoint Configuration
      CertType: "zmq,der"
    networks:
      - eii
    ports:
      - 65003:65003

    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
      - "vol_opcua:/tmp"
    secrets:
      - ca_etcd
      - etcd_OpcuaExport_cert
      - etcd_OpcuaExport_key
      - opcua_client_cert

volumes:
  vol_opcua:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:
  etcd_OpcuaExport_cert:
    file: provision/Certificates/OpcuaExport/OpcuaExport_client_certificate.pem
  etcd_OpcuaExport_key:
    file: provision/Certificates/OpcuaExport/OpcuaExport_client_key.pem
  opcua_client_cert:
    file: provision/Certificates/opcua/opcua_client_certificate.der
